name: wf-ci-stagging
on:
  pull_request:
    branches:
      - "release/**"
jobs:
  ci-stagging-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{github.ref}}
      - name: lint
        run: |
          npx htmlhint "**/*.html"
          npx stylelint "**/*.css"
      - name: build
        run: npx parcel build "./src/index.html"  --dist-dir "./dist" --public-url "./"
        